services:
  db:
    image: mysql:latest
    container_name: nebulazone-db-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nebulazone
      TZ: Asia/Seoul

  redis:
    image: redis:latest
    container_name: nebulazone-redis
    ports:
      - "6379:6379"

  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379

  prometheus:
    image: prom/prometheus
    container_name: nebulazone-prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: nebulazone-grafana
    ports:
      - "3000:3000"

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nebulazone-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.1
    container_name: nebulazone-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.18.1
    container_name: logstash
    ports:
      - "9600:9600"
      - "5044:5044"
    volumes:
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/pipeline/pipeline1.conf:/usr/share/logstash/pipeline/pipeline1.conf
      - ./logstash/pipeline/pipeline2.conf:/usr/share/logstash/pipeline/pipeline2.conf
    environment:
      - XPACK_MONITORING_ENABLED=false

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.18.1
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/var/log/app
    depends_on:
      - logstash
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    command: [ "--strict.perms=false" ]

volumes:
  es-data:
